#!/usr/bin/env python3
"""Phase-1 mechanical split of docs/dead-ends.md into topic files (organize-only).

Contract: every content line of the original moves VERBATIM into exactly one
topic file, in original order; nothing is reworded, merged, dropped, or added
below each file's marker line. This script is the whole mechanism — it
validates the manifest (every block start is a real top-level block), writes
the files, then re-reads them from disk and reassembles the blocks in manifest
order, requiring the result to be BYTE-IDENTICAL to docs/dead-ends.md.

Files named in PHASE2_RELEASED have left phase 1: they are maintained IN PLACE
(revisions in git), are NEVER regenerated by this script, and are excluded
from the byte check — the check then proves the NON-released files still carry
their original spans verbatim. Releasing a file here is one line, added in the
same commit as that file's first phase-2 edit.

Exit 0 = files written and the non-released reconstruction identical; non-zero
= do not trust the split. Run: python3 docs/dead-ends/split.py
"""
import hashlib
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
SRC = HERE.parent / "dead-ends.md"
MARK = "<!-- == verbatim content from docs/dead-ends.md below this marker == -->"

PREFACE = """Phase-1 split of `docs/dead-ends.md` (organize-only; the original file stays
the live registry until the merge is decided). Content below the marker is
VERBATIM from the original, so in-text "above"/"below"/section references may
point at entries now homed in a sibling file — `README.md` in this directory
carries the index, the assignment rule, and the block manifest that resolves
them. Do not edit below the marker while the refactor is in phase 1; the split
is re-derivable from the manifest and verified byte-identical by `split.py`.
"""

TITLES = {
    "00-registry-contract.md": "Registry contract — evidence classes, subject axis, write/delete rules",
    "terminology-dust.md": "Terminology — the 'dust' ban and the four senses",
    "acquisition-checklist.md": "Acquisition checklist — the real quality lever",
    "intake-frame-qa.md": "Intake — frame QA, culling, drift/mount instruments",
    "calibration-flats.md": "Calibration — synthetic sky flats, darks, masters",
    "background-extraction.md": "Background extraction",
    "stretch-colour-judgment.md": "Stretch, colour, and judgment surfaces",
    "separation-deconv-psf.md": "Star separation, deconvolution, PSF treatment",
    "plate-solving-wcs.md": "Plate solving and WCS consumption",
    "registration-distortion.md": "Registration and lens distortion (wide-field untracked)",
    "stacking-compose.md": "Stacking, groups, and the sub-stack compose",
    "lunar-planetary.md": "Lunar / planetary registration",
    "star-shape-optics.md": "Star-shape, PSF, and optics measurement",
    "siril-behaviors.md": "Siril and tool silent behaviours",
    "measurement-discipline.md": "Measurement discipline — comparisons, floors, controls",
    "verification-traps.md": "Verification traps — checks and search instruments that lie",
    "evidence-provenance.md": "Evidence, records, and provenance",
}

# Files that have had their phase-2 pass: maintained in place, never
# regenerated, excluded from the byte check.
PHASE2_RELEASED = {
    "verification-traps.md",
    "evidence-provenance.md",
    "calibration-flats.md",
    "star-shape-optics.md",
    "stacking-compose.md",
    "registration-distortion.md",
    "plate-solving-wcs.md",
}


def fail(msg: str) -> None:
    print(f"FAIL: {msg}")
    sys.exit(1)


def main() -> None:
    src_text = SRC.read_text()
    src_lines = src_text.splitlines(keepends=True)
    total = len(src_lines)
    sha = hashlib.sha256(src_text.encode()).hexdigest()

    rows = []
    for raw in (HERE / "manifest.tsv").read_text().splitlines():
        if not raw.strip() or raw.startswith("#"):
            continue
        parts = raw.split("\t")
        if len(parts) != 3:
            fail(f"manifest row not 3 columns: {raw!r}")
        rows.append((int(parts[0]), parts[1], parts[2]))

    # -- validate ------------------------------------------------------------
    if rows[0][0] != 1:
        fail("first block must start at line 1")
    for (a, _, sa), (b, _, sb) in zip(rows, rows[1:]):
        if b <= a:
            fail(f"manifest not strictly increasing at {sb} (start {b} after {a})")
    if rows[-1][0] > total:
        fail(f"last start {rows[-1][0]} beyond source ({total} lines)")
    for start, _, slug in rows[1:]:
        line = src_lines[start - 1]
        if not (line.startswith("- ") or line.startswith("**") or line.startswith("#")):
            fail(f"start {start} ({slug}) is not a top-level block start: {line[:70]!r}")
    unknown = {d for _, d, _ in rows} - set(TITLES)
    if unknown:
        fail(f"manifest names files without titles: {sorted(unknown)}")
    if any(MARK in l for l in src_lines):
        fail("marker string occurs in the source; pick a different marker")

    # -- build ---------------------------------------------------------------
    spans = {}  # dest -> [(start, end)] in manifest (= original) order
    for i, (start, dest, _) in enumerate(rows):
        end = rows[i + 1][0] - 1 if i + 1 < len(rows) else total
        spans.setdefault(dest, []).append((start, end))

    stats = {}
    for dest, ss in spans.items():
        stats[dest] = (len(ss), sum(e - s + 1 for s, e in ss))
        if dest in PHASE2_RELEASED:
            continue
        body = "".join("".join(src_lines[s - 1 : e]) for s, e in ss)
        header = f"# {TITLES[dest]}\n\n{PREFACE}\n{MARK}\n"
        (HERE / dest).write_text(header + body)

    # -- verify: reassemble from the files ON DISK (released files' spans
    #    come from the source itself, so the check proves the others) --------
    queues = {}
    for dest in spans:
        if dest in PHASE2_RELEASED:
            continue
        text = (HERE / dest).read_text()
        idx = text.index(MARK + "\n")
        queues[dest] = text[idx + len(MARK) + 1 :].splitlines(keepends=True)
    pos = {d: 0 for d in queues}
    recon = []
    for i, (start, dest, _) in enumerate(rows):
        end = rows[i + 1][0] - 1 if i + 1 < len(rows) else total
        if dest in PHASE2_RELEASED:
            recon.append("".join(src_lines[start - 1 : end]))
            continue
        n = end - start + 1
        recon.append("".join(queues[dest][pos[dest] : pos[dest] + n]))
        pos[dest] += n
    leftover = {d: len(queues[d]) - pos[d] for d in queues if len(queues[d]) != pos[d]}
    identical = "".join(recon) == src_text

    # -- report --------------------------------------------------------------
    print(f"source: {SRC.name}  {total} lines  sha256 {sha}")
    print(f"blocks: {len(rows)}   files: {len(spans)}   released: {len(PHASE2_RELEASED)}")
    for dest in sorted(spans):
        b, n = stats[dest]
        tag = "  [phase 2 — not regenerated]" if dest in PHASE2_RELEASED else ""
        print(f"  {n:5d} lines  {b:3d} blocks  {dest}{tag}")
    print(f"leftover content lines after reassembly: {leftover if leftover else 0}")
    print(f"non-released files reassemble byte-identical to {SRC.name}: {identical}")
    sys.exit(0 if identical and not leftover else 2)


if __name__ == "__main__":
    main()
