#!/usr/bin/env bash
# Per-frame registration QA for a light set — the MEASURE step of the operating
# loop, and the input to the per-set culling decision (the ratified per-set cull policy).
#
#   run_frame_qa.sh <session-dir> <set> [--batch=76] [--z=3.5]
#
# Method: raw frames -> DEBAYERED FITS -> `register -2pass` in
# disk-bounded batches (ANALYSIS pass only: regdata lands in the .seq, no
# transformed frames are written) -> inspect_stage parses Siril's own per-frame
# regdata (FWHM / roundness / background / star count) -> the records are
# flattened per frame and cull_report flags the defect-side z outliers
# (WARN-only). The tracked summary lands at
# datasets/<session>/<set>/qa_work/frame_metrics.json.
#
# The metrics pooled across batches are reference-independent (FWHM/roundness/
# background/star count come from per-frame PSF fits); wfwhm mixes matching
# loss with drift distance so it is advisory only — cull_report never culls on
# it.
#
# Camera raws are DEBAYERED at convert, so `register` measures the GREEN layer
# at full resolution and the absolute FWHM is real. Registering the raw CFA
# mosaic instead samples a star's profile through alternating colour filters,
# which reads BROADER and LESS ROUND than the star is: measured on 20 frames of
# one 2.5s ISO1600 set, CFA 2.564 px / roundness 0.825 against debayered
# 2.350 px / 0.850 — a 9.1% FWHM inflation. Undebayered sampling was a disk
# adaptation for a 118 GB rig and is NOT a valid method for absolutes; the
# 3-layer working set costs ~147 MB/frame, which is why it is affordable now.
# Historic records made the old way carry the Bayer caveat in their own
# `method` string.
#
# THE `file` FIELD NAMES THE RAW AND THE NUMBERS ARE NOT MEASURED ON IT — so a
# per-frame value cannot be reproduced by opening the file its own record names.
# Every metric is regdata from `register -2pass` over the DEBAYERED conversion
# (`convert c -debayer` -> `c_*.fit` -> `c_.seq` -> `inspect_stage.py reg --seq`),
# while `records.jsonl`'s `file` carries the RAW's basename. Siril loads a NEF as
# the CFA MOSAIC (channels=1), which is a different quantity from what was
# recorded. MEASURED on 12 aug09/set-05 frames: analysing the named raw returns
# **0.151x** the recorded star count — one star in seven — against **0.855x** on
# the debayered conversion of those same frames
# (`datasets/aug09/set-05/sirilpy_work/analyse_probe.json`). A discrepancy that
# large reads as a BROKEN TOOL rather than as a wrong input, which is what makes it
# expensive rather than merely untidy. Reproducing from this record requires doing
# the conversion first.
#
# Batch sizing: the driver refuses a final batch of exactly ONE frame (Siril
# cannot build a sequence from a single frame) — it auto-shrinks the batch by
# one instead, and states it.
#
# LEAVES BEHIND (kept deliberately, gitignored, regenerated by a re-run):
# qa_work/frameqa/{metrics.jsonl,records.jsonl,cull_report.txt,siril.log} —
# the full per-frame records behind the tracked summary; the front end's
# Frames view reads records.jsonl when present. CLEANS: per-batch FITS/seq/
# raw links during the run, and the spent b*/ batch dirs at the end
# (records.jsonl already carries each frame's file name and batch).
#
# AS-WRITTEN STATUS: run end to end on this rig over 2,978 frames (5 sets of
# 578-600). That run is what exposed the rollup population bug fixed below —
# four clean sets passed and the one set carrying unregistered frames died at
# `st.median`, which is why the defect survived to a set that was 32% obscured.
# A set with ZERO unregistered frames produces a byte-identical record before
# and after that fix (verified on a 600-frame set); the added keys appear only
# when there is something to report. `distribution` and every z flag are over
# the REGISTERED frames alone — `registered` / `match_failed` /
# `match_failed_frames` carry the rest, and records.jsonl keeps every frame.
#
# This REPORTS; the cull applies per the STANDING USER POLICY: flagged
# defect-side frames exclude like any obstruction (the chain writes
# recipe.json's stack block with the flags as the why and reports the
# decision at the end); a hand-ratified stack block is never overwritten
# and always wins. cull_report itself stays WARN-only.
set -euo pipefail
REPO=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
source "$REPO/scripts/lib/siril_run.sh"   # serialized siril-cli invoker (BACKLOG:removal-conditions)
SESSION=${1:?usage: run_frame_qa.sh <session-dir> <set> [--batch=76] [--z=3.5]}
SET=${2:?missing <set>}
BATCH=76 Z=3.5
for a in "${@:3}"; do case "$a" in
  --batch=*) BATCH=${a#*=};; --z=*) Z=${a#*=};;
  *) echo "unknown arg $a" >&2; exit 1;;
esac; done
SESSION=$(cd "$SESSION" && pwd)
Q=$REPO/datasets/$(basename "$SESSION")/$SET/qa_work
P=$Q/frameqa
sir(){ siril_cli -d "$1" -s "$2" >> "$P/siril.log" 2>&1; }

# lights class: camera raws, or dedicated-astrocam FITS (registered as-is —
# a mono FITS set measures true, non-CFA FWHM; an OSC-FITS set re-decides
# its sampling per the removal-condition register before relying on absolutes)
mapfile -t SRC < <(find "$SESSION/$SET" -maxdepth 1 -type f \
  \( -iname '*.nef' -o -iname '*.dng' -o -iname '*.cr2' -o -iname '*.cr3' \
     -o -iname '*.arw' -o -iname '*.raf' \) | sort)
MODE=raw
if [ ${#SRC[@]} -eq 0 ]; then
  mapfile -t SRC < <(find "$SESSION/$SET" -maxdepth 1 -type f \
    \( -iname '*.fit' -o -iname '*.fits' \) | sort)
  MODE=fits
fi
n=${#SRC[@]}
[ "$n" -ge 8 ] || { echo "run_frame_qa: only $n light frames (raw or FITS) under $SESSION/$SET" >&2; exit 1; }
# Shrink until the remainder is not 1, not once: one decrement can land on 1
# again, because n = q*BATCH + 1 gives n mod (BATCH-1) = (q+1) mod (BATCH-1),
# which is 1 whenever q is a multiple of BATCH-1. At the default BATCH=76 that
# needs n=5701 (out of reach here), but the same code at --batch=12 fails on
# n=133/265/397 — ordinary set sizes — so the loop is the correct form either way.
if [ $((n % BATCH)) -eq 1 ]; then
  ORIGBATCH=$BATCH
  while [ "$BATCH" -gt 2 ] && [ $((n % BATCH)) -eq 1 ]; do BATCH=$((BATCH - 1)); done
  [ $((n % BATCH)) -ne 1 ] || { echo "run_frame_qa: $n frames leave a final batch of 1 at every batch size down to 2" >&2; exit 1; }
  echo "run_frame_qa: batch shrunk $ORIGBATCH -> $BATCH (a final batch of 1 cannot be sequenced; remainder is now $((n % BATCH)))"
fi
rm -rf "$P"; mkdir -p "$P"
echo "run_frame_qa: $n frames in $(( (n + BATCH - 1) / BATCH )) batches of $BATCH"

i=0; b=0
while [ $i -lt $n ]; do
  b=$((b+1))
  W=$P/b$b; mkdir -p "$W/src"
  batch_files=()
  for ((k=0; k<BATCH && i<n; k++, i++)); do
    ln -sf "${SRC[$i]}" "$W/src/$(basename "${SRC[$i]}")"
    batch_files+=("$(basename "${SRC[$i]}")")
  done
  printf '%s\n' "${batch_files[@]}" > "$W/files.txt"
  # -transf= is pinned even though this pass writes no product: it decides which
  # frames find enough pairs to register, and the registered/total ratio is a
  # RECORDED metric. No -interp= — `-2pass` resamples nothing, so pinning one
  # here would assert a knob this leg does not turn.
  printf 'requires 1.2.0\nset16bits\nsetcompress 0\nsetext fit\ncd %s\nconvert c -debayer -out=%s\ncd %s\nregister c -2pass -transf=homography\n' \
    "$W/src" "$W" "$W" > "$W/r.ssf"
  sir "$W" "$W/r.ssf"
  reg=$(grep -c '^R0' "$W/c_.seq" || true)
  [ "$reg" -gt 0 ] || reg=$(grep -c '^R1' "$W/c_.seq" || true)
  tot=$(ls "$W"/c_*.fit 2>/dev/null | wc -l)
  python3 "$REPO/scripts/qa/inspect_stage.py" reg --dir "$P" --seq "$W/c_.seq" \
    --registered "$reg" --total "$tot" --label "batch$b"
  rm -f "$W"/c_*.fit "$W"/*.seq; rm -rf "$W/src"
  echo "batch $b done ($i/$n)  $(df -h "$SESSION" | tail -1 | awk '{print $4" free"}')"
done

python3 - "$P" "$Q/frame_metrics.json" "$Z" "$MODE" <<'PY'
import json, os, re, statistics as st, sys
P, OUT, Z, MODE = sys.argv[1], sys.argv[2], float(sys.argv[3]), sys.argv[4]

entries = [json.loads(l) for l in open(f"{P}/metrics.jsonl")]
flat = []
for e in entries:
    b = int(e["label"].replace("batch", ""))
    # one name per LINE (never .split(): filenames may contain spaces)
    names = [l for l in open(f"{P}/b{b}/files.txt").read().splitlines() if l]
    for r in e["frames"]:
        fname = names[r["n"] - 1]
        # trailing digit run = the capture index (timeline() convention);
        # concatenating every digit invents a number on names like
        # "m20 1x1 Blue 0080-2"
        runs = re.findall(r"\d+", os.path.splitext(fname)[0])
        flat.append({"n": len(flat) + 1, "file": fname,
                     "frame_number": int(runs[-1]) if runs else None,
                     "fwhm": r["fwhm_px"], "wfwhm": r["wfwhm_px"], "round": r["round"],
                     "bg": r["bg16"], "nstars": r["nstars"],
                     "registered": bool(r["incl"]), "ref_copy": False,
                     "part": b, "batch": b})
with open(f"{P}/records.jsonl", "w") as f:
    for r in flat: f.write(json.dumps(r) + "\n")

# THE ANALYSIS POPULATION, DEFINED ONCE. A frame siril could not register
# carries NO regdata at all: inspect_stage sets every metric to None (its
# `has` test is nstars>0 or fwhm>0). That is not a missing measurement, it is
# the EXTREME of the defect being measured — zero stars found. Pooling it into
# a median is a TypeError, not a wrong number, and under `set -e` that killed
# this rollup before cull_report ran and before the record was written.
# MEASURED: aug14/set-05, 40 of 578 frames unregistered inside four cloud
# blocks, lost the whole set's tracked summary while records.jsonl sat
# complete on disk — so the failure LOOKED like the measurement had failed
# when only the rollup had. cull_report.py has always filtered to
# `registered`; this rollup did not, so ONE script carried TWO populations of
# the same frames. records.jsonl still keeps every frame (the failures are
# evidence, and naming them is what lets a reader find the worst of a set).
kept = [r for r in flat if r["registered"] and r["bg"] is not None]
failed = [r for r in flat if not (r["registered"] and r["bg"] is not None)]

def med(k): return round(st.median(r[k] for r in kept), 4)
def mn(k):  return round(min(r[k] for r in kept), 4)
def mx(k):  return round(max(r[k] for r in kept), 4)
blocks = []
for b in sorted({r["batch"] for r in flat}):
    rows = [r for r in kept if r["batch"] == b]
    nf = sum(1 for r in failed if r["batch"] == b)
    if not rows:
        # a whole batch inside an obscuration: state it, never omit the block
        blocks.append({"block": b, "frames": 0, "match_failed": nf,
                       "note": "every frame in this block failed registration "
                               "(no regdata) — nothing to summarise"})
        continue
    blk = {"block": b, "frames": len(rows),
           "fwhm": round(st.median(r["fwhm"] for r in rows), 3),
           "round": round(st.median(r["round"] for r in rows), 4),
           "stars": int(st.median(r["nstars"] for r in rows)),
           "bg16": int(st.median(r["bg"] for r in rows))}
    if nf:
        blk["match_failed"] = nf
    blocks.append(blk)

# defect-side robust z (same rule cull_report prints; recorded per flagged frame)
def rz(vals):
    m = st.median(vals); mad = st.median(abs(v - m) for v in vals) * 1.4826
    return m, max(mad, 1e-9)
side = {"fwhm": +1, "bg": +1, "round": -1, "nstars": -1}
stats = {k: rz([r[k] for r in kept]) for k in side} if kept else {}
flagged = []
for r in kept:
    flags = [k for k, s in side.items()
             if (r[k] - stats[k][0]) / stats[k][1] * s >= Z]
    if flags:
        flagged.append({"file": r["file"], "flags": flags,
                        **{k: r[k] for k in side}})

# Plate scale for the arcsec column. inspect_stage derives it from the header's
# FOCALLEN/XPIXSZ (206.265*px/fl), which is a NOMINAL figure: a zoom's marked
# focal length is approximate and breathes with focus, so it is documented as a
# solve HINT, not a measurement. When mount_probe has SOLVED this set, prefer
# the solve — measured 18.003 vs nominal 17.503 on july31/set-01, 2.8% low, and
# every fwhm_arcsec inherits the error. The solve runs on the EXTRACTED GREEN
# plane (half the full-res grid) while these frames are debayered at full res,
# so the recorded green-px scale halves into this domain.
scale = entries[0].get("pixel_scale_arcsec")
scale_source = "header FOCALLEN/XPIXSZ (nominal)"
try:
    # OUT is datasets/<session>/<set>/qa_work/frame_metrics.json; the
    # fingerprint is its grandparent's sibling record.
    with open(os.path.join(os.path.dirname(os.path.dirname(OUT)),
                           "fingerprint.json")) as fh:
        fp = json.load(fh)
    if fp.get("plate_scale_source") == "solved" and fp.get("plate_scale_arcsec_px"):
        scale = round(fp["plate_scale_arcsec_px"] / (2.0 if MODE == "raw" else 1.0), 4)
        scale_source = "astrometry.net solve (mount_probe), green-plane scale "\
                       "halved to the full-res debayered grid" if MODE == "raw" \
                       else "astrometry.net solve (mount_probe)"
except (OSError, ValueError, KeyError):
    pass
method = ("raw -> DEBAYERED FITS -> register -2pass in batches; per-frame "
          "FWHM/roundness/background/#stars pooled (reference-independent). "
          "Measured on the green layer at full resolution, so absolute FWHM is "
          "real (no Bayer-mosaic inflation)."
          if MODE == "raw" else
          "FITS lights (as-recorded) -> register -2pass in batches; per-frame "
          "FWHM/roundness/background/#stars pooled (reference-independent). "
          "Mono frames measure true, non-CFA FWHM.")
rec = {"tool": "Siril 1.4.4 register (2-pass) regdata via scripts/qa/inspect_stage.py; "
               "flagged at defect-side robust z >= %g (scripts/qa/cull_report.py rule)" % Z,
       "method": method,
       "frames_total": len(flat),
       "registered": sum(r["registered"] for r in flat),
       "match_failed": sum(not r["registered"] for r in flat),
       "pixel_scale_arcsec": scale,
       "pixel_scale_source": scale_source,
       "distribution": {
        "fwhm_px": {"median": med("fwhm"), "min": mn("fwhm"), "max": mx("fwhm")},
        "roundness": {"median": med("round"), "min": mn("round"), "max": mx("round")},
        "nstars": {"median": int(med("nstars")), "min": int(mn("nstars")), "max": int(mx("nstars"))},
        "bg16": {"median": int(med("bg")), "min": int(mn("bg")), "max": int(mx("bg"))}}
       if kept else {"fwhm_px": {"median": None}, "roundness": {"median": None},
                     "nstars": {"median": None}, "bg16": {"median": None},
                     "note": "no frame in this set registered — nothing to summarise"},
       "temporal_trend_contiguous_blocks": blocks,
       "flagged_defect_side_z": flagged,
       "cull_note": "STANDING POLICY (user-ratified): flagged defect-side frames "
                    "auto-cull in chain runs (recipe.json stack.exclude, written with "
                    "the flags as the why, reported at the end); a hand-ratified "
                    "stack block is never overwritten and always wins"}
# Name them. A count says a third of the set is gone; only the names say WHICH,
# and these are the worst frames in the set by construction.
if failed:
    rec["match_failed_frames"] = [r["file"] for r in failed]
json.dump(rec, open(OUT, "w"), indent=1)
print(f"wrote {OUT}  ({len(flagged)} flagged frame(s))")
PY
# cull_report REFUSES a population under 8 registered frames — it cannot pool a
# robust scale from fewer. That is a DATA condition, not a driver failure: the
# tracked record above is already written, so state it and carry on to the
# cleanup and the fingerprint refresh rather than dying under `set -e`/pipefail.
# Same root cause as the rollup above — a legitimate state of the data must not
# be able to kill the step that records it.
crc=0
python3 "$REPO/scripts/qa/cull_report.py" "$P/records.jsonl" --z "$Z" \
  > "$P/cull_report.txt" 2>&1 || crc=$?
tail -20 "$P/cull_report.txt"
[ "$crc" -eq 0 ] || echo "run_frame_qa: cull_report exited $crc — see $P/cull_report.txt; the frame_metrics.json record stands" >&2
rm -rf "$P"/b*

# Roundness just landed -> refresh the set's fingerprint so the mount
# cross-check (trail-vs-roundness) upgrades without being asked.
# Exit 2 = declared-vs-measured CONTRADICT: the QA record above is
# valid and stays, but the job ends loud so the mislabel is reconciled before
# anything builds on it. Any other refresh failure (e.g. no acquisition
# record yet) warns and leaves the QA result standing.
fprc=0
python3 "$REPO/scripts/lib/fingerprint.py" "$SESSION" "$SET" >/dev/null || fprc=$?
FPJ=$REPO/datasets/$(basename "$SESSION")/$SET/fingerprint.json
python3 - "$FPJ" <<'PY' || true
import json, sys
try:
    fp = json.load(open(sys.argv[1]))
except (OSError, ValueError):
    sys.exit(0)
mc = fp.get("mount_check") or {}
print(f"fingerprint: {fp.get('label')} | mount {mc.get('verdict')}"
      f" ({mc.get('method') or 'no instrument yet'})")
PY
if [ "$fprc" -eq 2 ]; then
  echo "run_frame_qa: declared-vs-measured mount CONTRADICT — reconcile the declaration before any build ($FPJ)" >&2
  exit 2
elif [ "$fprc" -ne 0 ]; then
  echo "run_frame_qa: fingerprint not derivable yet (missing acquisition record?) — the QA record stands" >&2
fi
echo "=== run_frame_qa DONE (per-frame records kept: $P/{metrics,records}.jsonl) ==="
